[theme]
base                     = "dark"
backgroundColor          = "#0B0F1A"
secondaryBackgroundColor = "#111827"
textColor                = "#F1F5F9"
primaryColor             = "#D10214"
font                     = "sans serif"
